### ISSUE TITLE
Top Bar

### ISSUE THREAD

**Issue by Co1lin** [Co1lin/iLearn-app#13]
评分功能：学科分类列表

- [x] 上面一个搜索框
- [ ] 搜索框右边是历史记录，点进去是访问过的实体的列表，点击实体进入缓存的详情页
- [ ] 搜索框下面是一堆 tab ，第一个为“综合”，后面的是九个学科（ tab 滑动切换）
- [ ] tab 最右侧是一个 edit 按钮，点击可以增删 tab 
- [ ] 可选：首页下拉搜索

**Comment by Co1lin** [comment]
参考： [仿网易新闻客户端分类排序](https://www.jianshu.com/p/7be162740a95)

**Comment by Achazwl** [comment]
duplicated with #16
